model_name : "lstm_1"
device : "cuda"
cache_dir : "data/torch/cache/train/lstm_1/"

dataset:
  input_features : ["%open", "%high", "%low", "%close", "%volume", "volume", "sma_5"]
  output_features : ["%sma_5_8"]
  sequence_length : 30
  timesteps : 8
  train_split : 0.7
  dataset_path : "data/csv/eod/raw/vnindex_raw_trainset_01-01-2016_31-12-2023.csv"
  max_row : 60000

model:
  lstm:
    input_size : 7
    hidden_size : 512
    num_layers : 1
    bias : True
    batch_first : True
    dropout : 0
    bidirectional : False
  fc1:
    output_size : 256
  dp1:
    dropout : 0.1
  fc2:
    output_size : 64
  dp2:
    dropout : 0.1
  fc3:
    output_size : 1

train:
  batch_size : 16
  num_epochs : 10
  learning_rate : 0.01
  optimizer : "adam"