model_name : "simple_lstm_1"
device : "cuda"
cache_dir : "data/torch/cache/train/simple_lstm/"

cache:
  use_cache : True

dataset:
  input_features : ["%sma_5_1"]
  output_features : ["%sma_5_2"]
  sequence_length : 10
  timesteps : 2
  train_split : 0.7
  dataset_path : "data/csv/eod/raw/vnindex_raw_trainset_01-01-2016_31-12-2023.csv"
  max_row : 1000

model:
  input_size : 1
  hidden_size : 16
  output_size : 1
  num_layers : 1
  bias : True
  batch_first : True
  dropout : 0.1
  bidirectional : False

training:
  batch_size : 32
  num_epochs : 30
  learning_rate : 0.05
  optimizer : "adam"